---
site_name: docs template
site_description: >-
  docs template for getting started
site_url: https://ajlab-gh.github.io/xperts-docs-demo
site_author: Alex Jammes

repo_name: "AJLab-GH/docs-template"
repo_url: "https://ajlab-gh.github.io/xperts-docs-demo/"
edit_uri: edit/main/docs/

# yamllint disable-line rule:line-length
copyright: "Try to be nice."

extra:
  annotate:
    json: [.s2]
  generator: false

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

#extra_css: [extra.css]
# extra_javascript: [extra.js]

theme:
  name: material
  #custom_dir: docs/overrides
  include_sidebar: false
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: grey
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: black
      scheme: slate
      toggle:
        icon: material/toggle-switch
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: "1-1"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: ajlab-gh
      repo: docs-template
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

nav:
  - "Introduction": "index.md"
  - "Getting Started":
      - "Accessing Your Azure Account": "start-azure-account.md"
      - "Deploying Your Lab Environment in Azure": "start-deploy.md"
  - "Hands on Labs":
      - "Lab 1 - Azure NSG & FortiGate": "hol-nsg-fgt-lab-1.md"
      - "Lab 2 - FortiWeb": "hol-fwb-lab-2.md"
  - Resources:
      - "Reference Architecture": "architecture.md"
      - "FortiWeb Bootstrap": "bootstrap.md"
      - "Cloud Role Play": "role-play.md"
      - "Download HoL (pdf)": "download-pdf.md"