---
site_name: XPERTS Academy - Cloud (Lab Guide Demo)
site_description: >-
  Using XPERTS 2023 Lab Guide to Demo User Contributions and Edits
site_url: https://ajlab-gh.github.io/xperts-docs-demo
site_author: Alex Jammes

repo_name: "AJLab-GH/docs-template"
repo_url: "https://ajlab-gh.github.io/xperts-docs-demo/"
edit_uri: "edit/main/docs/"

theme:
  name: material
  logo: img/fortinet.svg
  favicon: img/fortinet.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: white
      accent: white
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Remove Default Footer
extra:
  generator: false

# Footer
copyright: Try and be nice

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: On this page

  # Python Markdown Extensions
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - search
  - glightbox
  - with-pdf:
      author: Fortinet Canada CSE Team
      copyright: Last Update November 2023

      cover: true
      back_cover: false
      cover_title: Fortinet XPA2023 - ZTNA Track
      cover_subtitle: Hands-On Lab
      # custom_template_path: TEMPLATES PATH
      #
      # toc_title: TOC TITLE TEXT
      # heading_shift: false
      toc_level: 3
      ordered_chapter_level: 2
      # excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      # exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      # convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      # two_columns_level: 3
      #
      # render_js: true
      # headless_chrome_path: headless-chromium
      #
      output_path: download/fortinet-secure-cloud-blueprint-hol.pdf
      # enabled_if_env: ENABLE_PDF_EXPORT
      #
      # debug_html: true
      # show_anchors: true
      # verbose: true

nav:
  - "Introduction": "index.md"
  - "Getting Started":
      - "Accessing Your Azure Account": "start-azure-account.md"
      - "Deploying Your Lab Environment in Azure": "start-deploy.md"
  - "Hands on Labs":
      - "Lab 1 - Azure NSG & FortiGate": "hol-nsg-fgt-lab-1.md"
      - "Lab 2 - FortiWeb": "hol-fwb-lab-2.md"
  - Resources:
      - "Reference Architecture": "architecture.md"
      - "FortiWeb Bootstrap": "bootstrap.md"
      - "Cloud Role Play": "role-play.md"
      - "Download HoL (pdf)": "download-pdf.md"
